.MODEL SMALL
.STACK 100H
.DATA
NL EQU 0AH, 0DH
MSG1 DB "ENTER THE FIRST NUMBER: $" ; VAR1 IS A BYTE TYPE VARIABLE WHICH HASN'T BEEN INITIALIZED
MSG2 DB NL,"Enter the second NUMBER: $"
NUM1 DB ?
NUM2 DB ?
RESULT DB ?



.CODE
MAIN PROC
;INITIALIZING DATA SEGMENT
MOV AX,@DATA ;@DATA RETURNS THE DATA SEGMENT NUMBER
MOV DS,AX ;DS = DATA SEGMENT REGISTER

;TAKING INPUT  

MOV AH,9
LEA DX, MSG1
INT 21H

MOV AH,1
INT 21H
MOV NUM1,AL
SUB NUM1,30H ;CONVERTING ASCII TO DIGIT    




MOV AH,9
LEA DX, MSG1
INT 21H

MOV AH,1
INT 21H
MOV NUM2,AL
SUB NUM2,30H ;CONVERTING ASCII TO DIGIT  


;ADDING THEM UP
MOV BL,NUM1 ;BL = NUM1
ADD BL,NUM2 ;BL = NUM1 + NUM2
MOV RESULT,BL ;RESULT = NUM1 + NUM2
ADD RESULT,30H ;CONVERTING DIGIT TO ASCII
;DISPLAY
MOV AH,2
MOV DL,'='
INT 21H

MOV DL,RESULT
INT 21H

MOV AH,4CH
INT 21H
MAIN ENDP
END MAIN